INSERT INTO categories (name, description, icon_name)
VALUES
    ('Fiction', 'Modern and literary fiction selected for immersive reading and elegant shelf presence.', 'BookOpen'),
    ('Non-Fiction', 'Essays, biographies, and reportage for readers who prefer the world rendered with precision.', 'Scroll'),
    ('Sci-Fi & Fantasy', 'Speculative worlds, strange futures, and mythic journeys in finely crafted editions.', 'RocketLaunch'),
    ('History & Antiquity', 'Civilizations, empires, and turning points presented with depth and authority.', 'Bank'),
    ('Mystery & Crime', 'Investigations, noir classics, and tightly wound suspense for late-night reading.', 'MagnifyingGlass'),
    ('Classic Literature', 'Enduring novels and plays in collector-friendly editions for lasting libraries.', 'Bookmarks')
ON CONFLICT (name) DO UPDATE
SET
    description = EXCLUDED.description,
    icon_name = EXCLUDED.icon_name;

INSERT INTO books (
    title,
    author,
    isbn,
    edition,
    description,
    stock_quantity,
    price,
    original_price,
    return_policy,
    publisher,
    page_count,
    language,
    publication_year,
    cover_image_url,
    cover_color,
    category_id,
    created_at,
    updated_at,
    version
)
VALUES
    (
        'The Night Archive',
        'Elena Marlowe',
        '9780306400001',
        'Collector''s Edition',
        'A layered literary mystery set inside a decaying private library where letters and ledgers reveal a buried inheritance.',
        8,
        42.00,
        55.00,
        '30-day returns',
        'Aurelia House',
        368,
        'English',
        2021,
        NULL,
        '#1C1917',
        (SELECT id FROM categories WHERE name = 'Fiction'),
        CURRENT_TIMESTAMP - INTERVAL '18 days',
        CURRENT_TIMESTAMP - INTERVAL '18 days',
        0
    ),
    (
        'The Glass Orchard',
        'Miriam Vale',
        '9780306400002',
        'Hardcover',
        'An intimate family novel about inheritance, ambition, and the careful ruin that follows long-guarded secrets.',
        12,
        34.00,
        NULL,
        '30-day returns',
        'Fen Ledger Press',
        312,
        'English',
        2019,
        NULL,
        '#7A2222',
        (SELECT id FROM categories WHERE name = 'Fiction'),
        CURRENT_TIMESTAMP - INTERVAL '16 days',
        CURRENT_TIMESTAMP - INTERVAL '16 days',
        0
    ),
    (
        'Letters from the Observatory',
        'Jonas Thorne',
        '9780306400003',
        'Deluxe Clothbound',
        'A reflective epistolary novel in which an isolated astronomer records a final season beneath a failing dome.',
        5,
        48.00,
        60.00,
        '30-day returns',
        'Meridian Editions',
        284,
        'English',
        2020,
        NULL,
        '#A38241',
        (SELECT id FROM categories WHERE name = 'Fiction'),
        CURRENT_TIMESTAMP - INTERVAL '14 days',
        CURRENT_TIMESTAMP - INTERVAL '14 days',
        0
    ),
    (
        'The Cartographer''s Silence',
        'R. J. Whitlock',
        '9780306400004',
        'Annotated Edition',
        'A narrative history of vanished maps, political borders, and the deliberate art of omission.',
        10,
        38.00,
        NULL,
        '30-day returns',
        'Civic Atlas Press',
        336,
        'English',
        2018,
        NULL,
        '#78716C',
        (SELECT id FROM categories WHERE name = 'Non-Fiction'),
        CURRENT_TIMESTAMP - INTERVAL '13 days',
        CURRENT_TIMESTAMP - INTERVAL '13 days',
        0
    ),
    (
        'Salt, Silk, and Empire',
        'Nadia Perin',
        '9780306400005',
        'Hardcover',
        'A sweeping account of luxury trade routes and the merchants who shaped courts from Venice to Samarkand.',
        7,
        44.00,
        52.00,
        '30-day returns',
        'Ivory Gate Books',
        402,
        'English',
        2022,
        NULL,
        '#C5A059',
        (SELECT id FROM categories WHERE name = 'Non-Fiction'),
        CURRENT_TIMESTAMP - INTERVAL '12 days',
        CURRENT_TIMESTAMP - INTERVAL '12 days',
        0
    ),
    (
        'A Cabinet of Useful Doubts',
        'Clara M. Hsu',
        '9780306400006',
        'Paperback',
        'Elegant essays on skepticism, evidence, and the value of changing one''s mind without surrendering conviction.',
        0,
        24.00,
        NULL,
        '30-day returns',
        'North Quill',
        248,
        'English',
        2023,
        NULL,
        '#D8D2C4',
        (SELECT id FROM categories WHERE name = 'Non-Fiction'),
        CURRENT_TIMESTAMP - INTERVAL '10 days',
        CURRENT_TIMESTAMP - INTERVAL '10 days',
        0
    ),
    (
        'Starfall at Orison Gate',
        'Talia Voss',
        '9780306400007',
        'Collector''s Edition',
        'An imperial courier crosses a dying starlane carrying a sealed treaty that may end a century of celestial war.',
        14,
        46.00,
        58.00,
        '30-day returns',
        'Lumen Forge',
        416,
        'English',
        2024,
        NULL,
        '#5C1717',
        (SELECT id FROM categories WHERE name = 'Sci-Fi & Fantasy'),
        CURRENT_TIMESTAMP - INTERVAL '9 days',
        CURRENT_TIMESTAMP - INTERVAL '9 days',
        0
    ),
    (
        'The Brass Citadel',
        'Ilya Fen',
        '9780306400008',
        'Hardcover',
        'A tactician, a dissident archivist, and a clockwork city collide in a fantasy of siege, memory, and oathbound machines.',
        9,
        40.00,
        NULL,
        '30-day returns',
        'Lumen Forge',
        390,
        'English',
        2022,
        NULL,
        '#292524',
        (SELECT id FROM categories WHERE name = 'Sci-Fi & Fantasy'),
        CURRENT_TIMESTAMP - INTERVAL '8 days',
        CURRENT_TIMESTAMP - INTERVAL '8 days',
        0
    ),
    (
        'Moonwater and Iron',
        'Sera Bell',
        '9780306400009',
        'Illustrated Edition',
        'A folkloric quest through drowned forests and broken kingdoms, framed by luminous illustrations and marginalia.',
        4,
        52.00,
        64.00,
        '30-day returns',
        'Arc Lantern Press',
        352,
        'English',
        2021,
        NULL,
        '#A38241',
        (SELECT id FROM categories WHERE name = 'Sci-Fi & Fantasy'),
        CURRENT_TIMESTAMP - INTERVAL '7 days',
        CURRENT_TIMESTAMP - INTERVAL '7 days',
        0
    ),
    (
        'The Last Republic of Bronze',
        'Marcus Elian',
        '9780306400010',
        'Scholarly Edition',
        'A vivid reconstruction of a maritime republic built on bronze, debt, and ritual diplomacy at the edge of collapse.',
        6,
        50.00,
        NULL,
        '30-day returns',
        'Forum Archive',
        438,
        'English',
        2017,
        NULL,
        '#6B5B4B',
        (SELECT id FROM categories WHERE name = 'History & Antiquity'),
        CURRENT_TIMESTAMP - INTERVAL '6 days',
        CURRENT_TIMESTAMP - INTERVAL '6 days',
        0
    ),
    (
        'Courts of Marble and Dust',
        'Helena Arcos',
        '9780306400011',
        'Hardcover',
        'An account of law, ceremony, and imperial spectacle from the late antique Mediterranean to the early medieval court.',
        11,
        39.00,
        NULL,
        '30-day returns',
        'Forum Archive',
        364,
        'English',
        2020,
        NULL,
        '#E8E5DC',
        (SELECT id FROM categories WHERE name = 'History & Antiquity'),
        CURRENT_TIMESTAMP - INTERVAL '5 days',
        CURRENT_TIMESTAMP - INTERVAL '5 days',
        0
    ),
    (
        'The Silk Road Ledger',
        'Farid Karim',
        '9780306400012',
        'Deluxe Paperback',
        'Merchants, monasteries, and border officials emerge from translated account books along a thousand-mile trade corridor.',
        3,
        31.00,
        37.00,
        '30-day returns',
        'Civic Atlas Press',
        288,
        'English',
        2019,
        NULL,
        '#C5A059',
        (SELECT id FROM categories WHERE name = 'History & Antiquity'),
        CURRENT_TIMESTAMP - INTERVAL '4 days',
        CURRENT_TIMESTAMP - INTERVAL '4 days',
        0
    ),
    (
        'Ashes on Briar Lane',
        'Vivian Crowe',
        '9780306400013',
        'Hardcover',
        'A rain-soaked murder investigation in a provincial town where every witness is curated and every memory has a price.',
        15,
        29.00,
        NULL,
        '30-day returns',
        'Black Lantern Crime',
        320,
        'English',
        2024,
        NULL,
        '#7A2222',
        (SELECT id FROM categories WHERE name = 'Mystery & Crime'),
        CURRENT_TIMESTAMP - INTERVAL '3 days',
        CURRENT_TIMESTAMP - INTERVAL '3 days',
        0
    ),
    (
        'The Winter Detective',
        'Owen Mercer',
        '9780306400014',
        'Collector''s Edition',
        'An aging investigator reopens a cathedral heist from thirty years earlier when a single silver key resurfaces.',
        0,
        36.00,
        44.00,
        '30-day returns',
        'Black Lantern Crime',
        298,
        'English',
        2021,
        NULL,
        '#1C1917',
        (SELECT id FROM categories WHERE name = 'Mystery & Crime'),
        CURRENT_TIMESTAMP - INTERVAL '2 days',
        CURRENT_TIMESTAMP - INTERVAL '2 days',
        0
    ),
    (
        'Pale Ink Conspiracy',
        'Celeste Rowan',
        '9780306400015',
        'Paperback',
        'A rare-book appraiser uncovers forged provenance papers that point toward a network of elegant literary fraud.',
        13,
        27.00,
        NULL,
        '30-day returns',
        'Rook & Key',
        276,
        'English',
        2023,
        NULL,
        '#4F463F',
        (SELECT id FROM categories WHERE name = 'Mystery & Crime'),
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        CURRENT_TIMESTAMP - INTERVAL '1 day',
        0
    ),
    (
        'The Odyssey',
        'Homer',
        '9780306400016',
        'Clothbound Edition',
        'The epic voyage of Odysseus rendered in a stately edition designed for rereading and display.',
        9,
        33.00,
        NULL,
        '30-day returns',
        'Aurelia Classics',
        560,
        'English',
        1998,
        NULL,
        '#292524',
        (SELECT id FROM categories WHERE name = 'Classic Literature'),
        CURRENT_TIMESTAMP - INTERVAL '11 hours',
        CURRENT_TIMESTAMP - INTERVAL '11 hours',
        0
    ),
    (
        'Pride and Prejudice',
        'Jane Austen',
        '9780306400017',
        'Collector''s Edition',
        'A refined edition of Austen''s comedy of manners, balancing wit, social scrutiny, and romantic intelligence.',
        18,
        30.00,
        36.00,
        '30-day returns',
        'Aurelia Classics',
        432,
        'English',
        2004,
        NULL,
        '#D8D2C4',
        (SELECT id FROM categories WHERE name = 'Classic Literature'),
        CURRENT_TIMESTAMP - INTERVAL '8 hours',
        CURRENT_TIMESTAMP - INTERVAL '8 hours',
        0
    ),
    (
        'Hamlet',
        'William Shakespeare',
        '9780306400018',
        'Annotated Edition',
        'A performance-minded text with scholarly notes for readers who want both drama and close reading in one volume.',
        7,
        26.00,
        NULL,
        '30-day returns',
        'Aurelia Classics',
        288,
        'English',
        2015,
        NULL,
        '#5C1717',
        (SELECT id FROM categories WHERE name = 'Classic Literature'),
        CURRENT_TIMESTAMP - INTERVAL '5 hours',
        CURRENT_TIMESTAMP - INTERVAL '5 hours',
        0
    )
ON CONFLICT (isbn) DO UPDATE
SET
    title = EXCLUDED.title,
    author = EXCLUDED.author,
    edition = EXCLUDED.edition,
    description = EXCLUDED.description,
    stock_quantity = EXCLUDED.stock_quantity,
    price = EXCLUDED.price,
    original_price = EXCLUDED.original_price,
    return_policy = EXCLUDED.return_policy,
    publisher = EXCLUDED.publisher,
    page_count = EXCLUDED.page_count,
    language = EXCLUDED.language,
    publication_year = EXCLUDED.publication_year,
    cover_image_url = EXCLUDED.cover_image_url,
    cover_color = EXCLUDED.cover_color,
    category_id = EXCLUDED.category_id,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at,
    version = EXCLUDED.version;
